// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

#if canImport(AppleProductTypes)
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Life XP",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Life XP",
            targets: ["AppModule"],
            bundleIdentifier: "com.ayoub.LifeXP",
            teamIdentifier: "26TUM3453K",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .checkmark),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
#else
import PackageDescription

// Fallback manifest for environments where AppleProductTypes is unavailable
// (e.g. `swift build` outside Swift Playgrounds). This keeps the package
// loadable so the source can be inspected without the Playgrounds SDK.
let package = Package(
    name: "Life XP",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .executable(name: "Life XP", targets: ["AppModule"])
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
#endif
