// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Life XP",
    defaultLocalization: "en",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Life XP",
            targets: ["AppModule"],
            bundleIdentifier: "com.ayoub.LifeXP",
            teamIdentifier: "26TUM3453K",
            displayVersion: "0.8.91",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .lifestyle
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Tests"],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        ),
        .testTarget(
            name: "AppModuleTests",
            dependencies: [
                "AppModule"
            ],
            path: "Tests"
        )
    ]
)
